import "./globals.css";
import { Mulish } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./nav/page";
import SideBar from "./sidebar/page";
const mulish = Mulish({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <>
          <UserProvider>
            <Navbar />
           <SideBar/>
            {children}
          </UserProvider>
        </>
      </body>
    </html>
  );
}
